/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IdRegistry } from './IdRegistry'
export type { NameRegistry } from './NameRegistry'

export { IdRegistry__factory } from './factories/IdRegistry_factory'
export { NameRegistry__factory } from './factories/NameRegistry_factory'
